CREATE TABLE `real_time` (
  `id` bigint(30) NOT NULL AUTO_INCREMENT,
  `date` int(8) DEFAULT NULL COMMENT '日期',
  `time` varchar(10) DEFAULT NULL COMMENT '时间',
  `symbol` varchar(12) DEFAULT NULL COMMENT '代码',
  `timestamp` int(15) DEFAULT NULL COMMENT '时间戳',
  `name` varchar(20) DEFAULT NULL COMMENT '名称',
  `open` float(10,2) DEFAULT NULL COMMENT '今开',
  `settlement` float(10,2) DEFAULT NULL COMMENT '昨收',
  `trade` float(10,2) DEFAULT NULL COMMENT '最新价',
  `high` float(10,2) DEFAULT NULL COMMENT '最高',
  `low` float(10,2) DEFAULT NULL COMMENT '最低',
  `current_buy` float(10,2) DEFAULT NULL COMMENT '竞买价',
  `current_sell` float(10,2) DEFAULT NULL COMMENT '竞卖价',
  `volume` int(15) DEFAULT NULL COMMENT '成交量/手',
  `amount` float(20,2) DEFAULT NULL COMMENT '成交额/元',
  `b1c` int(10) DEFAULT NULL COMMENT '买1量',
  `b1p` float(10,2) DEFAULT NULL COMMENT '买1价',
  `b2c` int(10) DEFAULT NULL COMMENT '买2量',
  `b2p` float(10,2) DEFAULT NULL COMMENT '买2价',
  `b3c` int(10) DEFAULT NULL COMMENT '买3量',
  `b3p` float(10,2) DEFAULT NULL COMMENT '买3价',
  `b4c` int(10) DEFAULT NULL COMMENT '买4量',
  `b4p` float(10,2) DEFAULT NULL COMMENT '买4价',
  `b5c` int(10) DEFAULT NULL COMMENT '买5量',
  `b5p` float(10,2) DEFAULT NULL COMMENT '买5价',
  `s1c` int(10) DEFAULT NULL COMMENT '卖1量',
  `s1p` float(10,2) DEFAULT NULL COMMENT '卖1价',
  `s2c` int(10) DEFAULT NULL COMMENT '卖2量',
  `s2p` float(10,2) DEFAULT NULL COMMENT '卖2价',
  `s3c` int(10) DEFAULT NULL COMMENT '卖3量',
  `s3p` float(10,2) DEFAULT NULL COMMENT '卖3价',
  `s4c` int(10) DEFAULT NULL COMMENT '卖4量',
  `s4p` float(10,2) DEFAULT NULL COMMENT '卖4价',
  `s5c` int(10) DEFAULT NULL COMMENT '卖5量',
  `s5p` float(10,2) DEFAULT NULL COMMENT '卖5价',
  `unkown` varchar(20) DEFAULT NULL COMMENT '未知',
  PRIMARY KEY (`id`),
  KEY `d` (`date`),
  KEY `s` (`symbol`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
